# Generated by Django 2.2 on 2021-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='题目答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=500, verbose_name='题目详情'),
        ),
    ]
