# Generated by Django 2.2 on 2021-02-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20210108_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
