# Generated by Django 2.2 on 2021-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210112_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
